version: "3.9"

services:
  backend:
    image: ghcr.io/bruno7kp/zero-backend:main
    env_file: backend/.env.production
    environment:
      RUN_MIGRATIONS: "true"
      CACHE_OPTIMIZE: "true"
    networks:
      - zero-net
    volumes:
      - app-storage:/var/www/html/storage
      - app-cache:/var/www/html/bootstrap/cache
      - sqlite-data:/var/www/html/database

  web:
    image: ghcr.io/bruno7kp/zero-web:main
    depends_on:
      - backend
    networks:
      - zero-net
    ports:
      - "8081:80"  # expõe internamente para Apache proxy -> 8081


volumes:
  app-storage:
  app-cache:
  sqlite-data:

networks:
  zero-net:
    driver: bridge

