version: "3.9"

services:
  backend:
    image: ghcr.io/bruno7kp/zero-backend:main
    environment:
      RUN_MIGRATIONS: "true"
      CACHE_OPTIMIZE: "true"
      # (Optional debug) OAUTH_DIAG: "1"
      # Hybrid flag: if set to "true" ativa Socialite para redirect e callback; se "false" usa fluxo manual
      OAUTH_USE_SOCIALITE: "false"
    networks:
      - zero-net
    volumes:
      - ./backend/.env.production:/var/www/html/.env.production:ro
      - app-storage:/var/www/html/storage
      - app-cache:/var/www/html/bootstrap/cache
      - sqlite-data:/var/www/html/database

  web:
    image: ghcr.io/bruno7kp/zero-web:main
    depends_on:
      - backend
    networks:
      - zero-net
    ports:
      - "8081:80"  # expõe internamente para Apache proxy -> 8081
    volumes:
      # Mount nginx config to apply updates without rebuilding image
      - ./docker/nginx/nginx.fullstack.prod.conf:/etc/nginx/conf.d/default.conf:ro


volumes:
  app-storage:
  app-cache:
  sqlite-data:

networks:
  zero-net:
    driver: bridge

