## Frontend production image (build + static serving through nginx)

FROM node:22-alpine AS build
WORKDIR /app
COPY ../../frontend/package*.json ./
RUN npm ci --no-audit --no-fund
COPY ../../frontend .
RUN npm run build

# Nginx stage to serve static assets
FROM nginx:stable-alpine AS runtime
WORKDIR /usr/share/nginx/html

# Remove default config e usa config otimizada para produção SPA
COPY ../../docker/nginx/nginx.frontend.prod.conf /etc/nginx/conf.d/default.conf

# Copy built assets
COPY --from=build /app/dist .

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
