server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php;

    # Todas as requisições que não são da API são enviadas para o frontend
    location / {
        try_files $uri @frontend;
    }

    # Todas as requisições para /api são enviadas para o Laravel
    location /api {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Este bloco lida com todas as requisições PHP usando FastCGI
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # O proxy que envia tudo para o contêiner do frontend
    location @frontend {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}